import io
import asyncio
from fastapi import FastAPI, HTTPException, Response
from pydantic import BaseModel
import edge_tts

app = FastAPI(title="Edge TTS Sidecar Microservice")

class TtsRequest(BaseModel):
    text: str
    voice: str = "en-US-AvaMultilingualNeural"

@app.post("/api/tts")
async def generate_tts(request: TtsRequest):
    if not request.text or not request.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty")
    
    try:
        communicate = edge_tts.Communicate(request.text, request.voice)
        audio_bytes = bytearray()
        
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                audio_bytes.extend(chunk["data"])
                
        if not audio_bytes:
            raise HTTPException(status_code=500, detail="No audio generated by Edge-TTS")
            
        return Response(content=bytes(audio_bytes), media_type="audio/mpeg")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"TTS Generation Error: {str(e)}")

@app.get("/health")
async def health_check():
    return {"status": "UP", "service": "edge-tts-sidecar"}
